# -*- coding: utf-8 -*-
"""Malaria_Detection_Cell_Information

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wlMBWX4CeW5AmgemjaNrkmJp1vva3o_o
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sbn
import numpy as np
import tensorflow_datasets as tfds

dataset,dataset_info = tfds.load('malaria',with_info = True, as_supervised = True, shuffle_files = True, split = ['train'])

TRAIN_RATIO = 0.6
VAL_RATIO = 0.1
TEST_RATIO = 0.1

dataset = tf.data.Dataset.range(10)
print(list(dataset.as_numpy_iterator()))

DATASET_SIZE = len(dataset)
train_dataset = dataset.take(int(0.8*DATASET_SIZE))

for data in dataset[0].take(4):
  print(data)
  break

